// Scrabble PT Study Transcript
// End-of-game transcript generated by Jeeves with export + palace integration

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FileText, Download, Loader2, Sparkles, Copy, Check, Map, BookOpen, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import type { StudyLogEntry } from './StudyLog';
import type { SelectedVerse } from './VerseSelectionScreen';

interface StudyTranscriptProps {
  entries: StudyLogEntry[];
  seedVerse?: SelectedVerse | null;
  totalScore: number;
  playerCount: number;
  onSave?: (transcript: string) => void;
}

export function StudyTranscript({
  entries,
  seedVerse,
  totalScore,
  playerCount,
  onSave,
}: StudyTranscriptProps) {
  const navigate = useNavigate();
  const [transcript, setTranscript] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  // Generate transcript with Jeeves
  const generateTranscript = async () => {
    if (entries.length === 0) {
      toast.error('No entries to generate transcript from');
      return;
    }

    setIsGenerating(true);

    try {
      // Build the prompt for Jeeves
      const entriesText = entries.map((e, i) => {
        const connectionLabel = i === 0
          ? '(Connected to the verse)'
          : `(Building on #${i}: ${entries[i - 1].playerName}'s "${entries[i - 1].cardName}" insight)`;
        const jeevesNote = e.jeevesJudgment ? `\n   Jeeves Commentary: "${e.jeevesJudgment}"` : '';
        return `${i + 1}. ${e.playerName} applied "${e.cardName}" (${e.cardCode}) ${connectionLabel}${e.isChristConnection ? ' [Christ Connection]' : ''}:\n   "${e.explanation}"${jeevesNote}`;
      }).join('\n\n');

      const prompt = seedVerse
        ? `You are Jeeves, a masterful Bible study editor. A group of students just completed a PT Scrabble game studying ${seedVerse.reference} ("${seedVerse.text}").

Each answer in the game had to build on the PREVIOUS answer, forming a chain of deepening insight. Here are the entries in order (including any Jeeves commentary that was given during the game):

${entriesText}

Your task: Create a POLISHED STUDY DOCUMENT that:

1. **WEAVE** all contributions AND Jeeves commentary into a flowing, cohesive Bible study — not a list, but a narrative that reads like a well-crafted study guide
2. **POLISH** each insight — fix any remaining grammar issues, deepen the theology, and strengthen the connections between each link in the chain
3. **SHOW THE CHAIN** — make it clear how each insight built upon the previous one, creating a growing tapestry of understanding
4. **INTEGRATE JEEVES GEMS** — weave the Jeeves commentary insights naturally into the narrative flow
5. **ADD BONUS GEMS** — after weaving together all work, add 2-3 additional insights (gems) that the group missed. These should be deeper connections, cross-references, or theological treasures
6. **CHRIST CONNECTION** — ensure the study culminates in how the passage points to Jesus
7. **PHOTOTHEOLOGY CODES** — at the end, list the PT room codes used (e.g., @No, CR, BL) with brief explanations

Format the document with clear sections, flowing paragraphs, and a concluding synthesis. Make it something the students would be proud to save and revisit.`
        : `Create a polished study document from these Phototheology principle connections (each answer built on the previous one, including Jeeves commentary):\n\n${entriesText}\n\nWeave all contributions into a flowing narrative, polish each insight, integrate Jeeves commentary, show how the chain of understanding grew, and add 2-3 bonus gems.`;

      const { data, error } = await supabase.functions.invoke('jeeves', {
        body: {
          message: prompt,
          context: 'scrabble_transcript',
        },
      });

      if (error) throw error;

      const generatedTranscript = data?.content || data?.response || data?.message || 'Unable to generate transcript.';

      // Add header and footer
      const fullTranscript = `# Phototheology Study: ${seedVerse ? seedVerse.reference : 'Scrabble PT Session'}
${seedVerse ? `\n> "${seedVerse.text}"\n> — ${seedVerse.reference}\n` : ''}
*${playerCount} ${playerCount === 1 ? 'student' : 'students'} | ${entries.length} insights chained | ${totalScore} points earned*

---

${generatedTranscript}

---

*Polished by Jeeves from a Scrabble PT study session*
*${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}*`;

      setTranscript(fullTranscript);
    } catch (err: any) {
      console.error('Error generating transcript:', err);

      // Fallback: create a simple transcript without AI
      const fallbackTranscript = createFallbackTranscript();
      setTranscript(fallbackTranscript);
      toast.info('Created basic transcript (AI unavailable)');
    } finally {
      setIsGenerating(false);
    }
  };

  // Fallback transcript without AI
  const createFallbackTranscript = (): string => {
    const entriesText = entries.map((e, i) =>
      `### ${i + 1}. ${e.cardName} (${e.cardCode}) - by ${e.playerName}${e.isChristConnection ? ' ✝️' : ''}

${e.explanation}
${e.jeevesJudgment ? `\n**Jeeves:** ${e.jeevesJudgment}` : ''}
*+${e.points} points*`
    ).join('\n\n---\n\n');

    return `# Scrabble PT Study Transcript
${seedVerse ? `\n## ${seedVerse.reference}\n> "${seedVerse.text}"\n` : ''}
**Players:** ${playerCount} | **Total Score:** ${totalScore} | **Contributions:** ${entries.length}

---

${entriesText}

---

*Scrabble PT game session*
*${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}*`;
  };

  // Copy to clipboard
  const handleCopy = async () => {
    if (!transcript) return;

    try {
      await navigator.clipboard.writeText(transcript);
      setCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy');
    }
  };

  // Download as file
  const handleDownload = () => {
    if (!transcript) return;

    const blob = new Blob([transcript], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scrabble-pt-study-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Downloaded!');
  };

  // Navigate to Mind Map with transcript content
  const handleTakeToMindMap = () => {
    if (!transcript) return;
    const verseRef = seedVerse?.reference || 'Scrabble PT Study';
    // Store in sessionStorage for mind map to pick up
    sessionStorage.setItem('scrabble_study_import', JSON.stringify({
      type: 'scrabble_transcript',
      title: `PT Scrabble: ${verseRef}`,
      content: transcript,
      verse: seedVerse?.reference || '',
      verseText: seedVerse?.text || '',
      entries: entries.map(e => ({
        cardCode: e.cardCode,
        cardName: e.cardName,
        explanation: e.explanation,
        jeevesInsight: e.jeevesJudgment,
        isChristConnection: e.isChristConnection,
      })),
    }));
    navigate('/mind-map');
    toast.success('Study loaded into Mind Map!');
  };

  // Navigate to Study Suite
  const handleTakeToStudy = () => {
    if (!transcript) return;
    sessionStorage.setItem('scrabble_study_import', JSON.stringify({
      type: 'scrabble_transcript',
      title: `PT Scrabble: ${seedVerse?.reference || 'Study Session'}`,
      content: transcript,
    }));
    navigate('/study');
    toast.success('Study loaded into Suite!');
  };

  // Save to suite
  const handleSave = () => {
    if (!transcript || !onSave) return;
    onSave(transcript);
    toast.success('Saved to your studies!');
  };

  // Auto-generate on mount if we have entries
  useEffect(() => {
    if (entries.length > 0 && !transcript && !isGenerating) {
      generateTranscript();
    }
  }, [entries.length]);

  return (
    <Card className="w-full max-w-2xl mx-auto">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5 text-primary" />
          Polished Study Transcript
        </CardTitle>
        <CardDescription>
          Your complete study session — polished by Jeeves with all insights woven together
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Generate button */}
        {!transcript && !isGenerating && (
          <Button onClick={generateTranscript} className="w-full">
            <Sparkles className="mr-2 h-4 w-4" />
            Generate Polished Transcript
          </Button>
        )}

        {/* Loading state */}
        {isGenerating && (
          <div className="flex flex-col items-center justify-center py-8 gap-4">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
            <p className="text-sm text-muted-foreground">Jeeves is polishing your study transcript...</p>
          </div>
        )}

        {/* Transcript display */}
        {transcript && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-4"
          >
            {/* Transcript content */}
            <div className="p-4 bg-muted rounded-lg max-h-96 overflow-y-auto">
              <pre className="whitespace-pre-wrap text-sm font-sans leading-relaxed">
                {transcript}
              </pre>
            </div>

            {/* Primary actions - save/copy/download */}
            <div className="flex flex-wrap gap-2">
              <Button variant="outline" onClick={handleCopy}>
                {copied ? <Check className="mr-2 h-4 w-4" /> : <Copy className="mr-2 h-4 w-4" />}
                {copied ? 'Copied!' : 'Copy'}
              </Button>
              <Button variant="outline" onClick={handleDownload}>
                <Download className="mr-2 h-4 w-4" />
                Download
              </Button>
              {onSave && (
                <Button onClick={handleSave} variant="outline">
                  <BookOpen className="mr-2 h-4 w-4" />
                  Save to Suite
                </Button>
              )}
              <Button variant="ghost" onClick={generateTranscript}>
                <Sparkles className="mr-2 h-4 w-4" />
                Regenerate
              </Button>
            </div>

            {/* Continue studying - take to other parts of the palace */}
            <div className="border-t pt-4">
              <p className="text-sm font-medium text-muted-foreground mb-3">Continue exploring this study:</p>
              <div className="flex flex-wrap gap-2">
                <Button onClick={handleTakeToMindMap} className="gap-2">
                  <Map className="h-4 w-4" />
                  Take to Mind Map
                  <ArrowRight className="h-3 w-3" />
                </Button>
                <Button variant="outline" onClick={handleTakeToStudy} className="gap-2">
                  <BookOpen className="h-4 w-4" />
                  Take to Study Suite
                  <ArrowRight className="h-3 w-3" />
                </Button>
              </div>
            </div>
          </motion.div>
        )}

        {/* Stats */}
        <div className="flex items-center justify-center gap-6 pt-4 border-t text-sm text-muted-foreground">
          <span>{entries.length} contributions</span>
          <span>{playerCount} player{playerCount !== 1 ? 's' : ''}</span>
          <span className="text-yellow-500 font-medium">{totalScore} total points</span>
        </div>
      </CardContent>
    </Card>
  );
}
