// Scrabble PT Study Transcript
// End-of-game transcript generated by Jeeves with export + palace integration

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { FileText, Download, Loader2, Sparkles, Copy, Check, Map, BookOpen, ArrowRight, ScrollText, Crown, Cross } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { formatJeevesResponse } from '@/lib/formatJeevesResponse';
import type { StudyLogEntry } from './StudyLog';
import type { SelectedVerse } from './VerseSelectionScreen';

interface StudyTranscriptProps {
  entries: StudyLogEntry[];
  seedVerse?: SelectedVerse | null;
  totalScore: number;
  playerCount: number;
  onSave?: (transcript: string) => void;
}

export function StudyTranscript({
  entries,
  seedVerse,
  totalScore,
  playerCount,
  onSave,
}: StudyTranscriptProps) {
  const navigate = useNavigate();
  const [transcript, setTranscript] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [copied, setCopied] = useState(false);

  // Generate transcript with Jeeves
  const generateTranscript = async () => {
    if (entries.length === 0) {
      toast.error('No entries to generate transcript from');
      return;
    }

    setIsGenerating(true);

    try {
      const entriesText = entries.map((e, i) => {
        const connectionLabel = i === 0
          ? '(Connected to the verse)'
          : `(Building on #${i}: ${entries[i - 1].playerName}'s "${entries[i - 1].cardName}" insight)`;
        const jeevesNote = e.jeevesJudgment ? `\n   Jeeves Commentary: "${e.jeevesJudgment}"` : '';
        return `${i + 1}. ${e.playerName} applied "${e.cardName}" (${e.cardCode}) ${connectionLabel}${e.isChristConnection ? ' [Christ Connection]' : ''}:\n   "${e.explanation}"${jeevesNote}`;
      }).join('\n\n');

      const prompt = seedVerse
        ? `You are Jeeves, a masterful Bible study editor. A group of students just completed a PT Scrabble game studying ${seedVerse.reference} ("${seedVerse.text}").

Each answer in the game had to build on the PREVIOUS answer, forming a chain of deepening insight. Here are the entries in order (including any Jeeves commentary that was given during the game):

${entriesText}

Your task: Create a POLISHED STUDY DOCUMENT that:

1. **WEAVE** all contributions AND Jeeves commentary into a flowing, cohesive Bible study — not a list, but a narrative that reads like a well-crafted study guide
2. **POLISH** each insight — fix any remaining grammar issues, deepen the theology, and strengthen the connections between each link in the chain
3. **SHOW THE CHAIN** — make it clear how each insight built upon the previous one, creating a growing tapestry of understanding
4. **INTEGRATE JEEVES GEMS** — weave the Jeeves commentary insights naturally into the narrative flow
5. **ADD BONUS GEMS** — after weaving together all work, add 2-3 additional insights (gems) that the group missed. These should be deeper connections, cross-references, or theological treasures
6. **CHRIST CONNECTION** — ensure the study culminates in how the passage points to Jesus
7. **PHOTOTHEOLOGY CODES** — at the end, list the PT room codes used (e.g., @No, CR, BL) with brief explanations

Format the document with clear markdown sections (## headings), flowing paragraphs, Scripture references in **bold**, and a concluding synthesis. Make it something the students would be proud to save and revisit.`
        : `Create a polished study document from these Phototheology principle connections (each answer built on the previous one, including Jeeves commentary):\n\n${entriesText}\n\nWeave all contributions into a flowing narrative with ## headings, **bold** Scripture references, polish each insight, integrate Jeeves commentary, show how the chain of understanding grew, and add 2-3 bonus gems.`;

      const { data, error } = await supabase.functions.invoke('jeeves', {
        body: {
          message: prompt,
          context: 'scrabble_transcript',
        },
      });

      if (error) throw error;

      const generatedTranscript = data?.content || data?.response || data?.message || 'Unable to generate transcript.';

      const fullTranscript = `## Phototheology Study: ${seedVerse ? seedVerse.reference : 'Scrabble PT Session'}
${seedVerse ? `\n> "${seedVerse.text}"\n> — ${seedVerse.reference}\n` : ''}
*${playerCount} ${playerCount === 1 ? 'student' : 'students'} | ${entries.length} insights chained | ${totalScore} points earned*

---

${generatedTranscript}

---

*Polished by Jeeves from a Scrabble PT study session*
*${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}*`;

      setTranscript(fullTranscript);
    } catch (err: any) {
      console.error('Error generating transcript:', err);
      const fallbackTranscript = createFallbackTranscript();
      setTranscript(fallbackTranscript);
      toast.info('Created basic transcript (AI unavailable)');
    } finally {
      setIsGenerating(false);
    }
  };

  const createFallbackTranscript = (): string => {
    const entriesText = entries.map((e, i) =>
      `### ${i + 1}. ${e.cardName} (${e.cardCode}) - by ${e.playerName}${e.isChristConnection ? ' ✝️' : ''}

${e.explanation}
${e.jeevesJudgment ? `\n**Jeeves:** ${e.jeevesJudgment}` : ''}
*+${e.points} points*`
    ).join('\n\n---\n\n');

    return `## Scrabble PT Study Transcript
${seedVerse ? `\n### ${seedVerse.reference}\n> "${seedVerse.text}"\n` : ''}
**Players:** ${playerCount} | **Total Score:** ${totalScore} | **Contributions:** ${entries.length}

---

${entriesText}

---

*Scrabble PT game session*
*${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}*`;
  };

  const handleCopy = async () => {
    if (!transcript) return;
    try {
      await navigator.clipboard.writeText(transcript);
      setCopied(true);
      toast.success('Copied to clipboard!');
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      toast.error('Failed to copy');
    }
  };

  const handleDownload = () => {
    if (!transcript) return;
    const blob = new Blob([transcript], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scrabble-pt-study-${new Date().toISOString().split('T')[0]}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Downloaded!');
  };

  const handleTakeToMindMap = () => {
    if (!transcript) return;
    const verseRef = seedVerse?.reference || 'Scrabble PT Study';
    sessionStorage.setItem('scrabble_study_import', JSON.stringify({
      type: 'scrabble_transcript',
      title: `PT Scrabble: ${verseRef}`,
      content: transcript,
      verse: seedVerse?.reference || '',
      verseText: seedVerse?.text || '',
      entries: entries.map(e => ({
        cardCode: e.cardCode,
        cardName: e.cardName,
        explanation: e.explanation,
        jeevesInsight: e.jeevesJudgment,
        isChristConnection: e.isChristConnection,
      })),
    }));
    navigate('/mind-map');
    toast.success('Study loaded into Mind Map!');
  };

  const handleTakeToStudy = () => {
    if (!transcript) return;
    sessionStorage.setItem('scrabble_study_import', JSON.stringify({
      type: 'scrabble_transcript',
      title: `PT Scrabble: ${seedVerse?.reference || 'Study Session'}`,
      content: transcript,
    }));
    navigate('/study');
    toast.success('Study loaded into Suite!');
  };

  const handleSave = () => {
    if (!transcript || !onSave) return;
    onSave(transcript);
    toast.success('Saved to your studies!');
  };

  useEffect(() => {
    if (entries.length > 0 && !transcript && !isGenerating) {
      generateTranscript();
    }
  }, [entries.length]);

  return (
    <Card className="w-full max-w-3xl mx-auto border-2 border-primary/20 shadow-xl bg-gradient-to-br from-card via-card to-primary/5">
      <CardHeader className="text-center pb-2">
        <div className="flex justify-center mb-3">
          <div className="p-3 rounded-full bg-primary/10 border border-primary/20">
            <ScrollText className="h-7 w-7 text-primary" />
          </div>
        </div>
        <CardTitle className="text-2xl font-bold tracking-tight">
          Polished Study Transcript
        </CardTitle>
        <CardDescription className="text-base">
          Your complete study session — polished by Jeeves with all insights woven together
        </CardDescription>
      </CardHeader>

      <CardContent className="space-y-5">
        {/* Generate button */}
        {!transcript && !isGenerating && (
          <motion.div initial={{ scale: 0.95 }} animate={{ scale: 1 }}>
            <Button onClick={generateTranscript} className="w-full h-12 text-base gap-2" size="lg">
              <Sparkles className="h-5 w-5" />
              Generate Polished Transcript
            </Button>
          </motion.div>
        )}

        {/* Loading state */}
        {isGenerating && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="flex flex-col items-center justify-center py-12 gap-4"
          >
            <div className="relative">
              <div className="absolute inset-0 rounded-full bg-primary/20 animate-ping" />
              <Loader2 className="h-10 w-10 animate-spin text-primary relative z-10" />
            </div>
            <p className="text-sm text-muted-foreground animate-pulse">
              Jeeves is polishing your study transcript...
            </p>
          </motion.div>
        )}

        {/* Beautified transcript display */}
        {transcript && (
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4 }}
            className="space-y-5"
          >
            {/* Rendered transcript using formatJeevesResponse */}
            <div className="rounded-xl border border-border/60 bg-background/80 shadow-inner max-h-[500px] overflow-y-auto">
              <div className="p-6 space-y-4 jeeves-response">
                {formatJeevesResponse(transcript)}
              </div>
            </div>

            {/* Primary actions */}
            <div className="flex flex-wrap gap-2 justify-center">
              <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5">
                {copied ? <Check className="h-4 w-4 text-green-500" /> : <Copy className="h-4 w-4" />}
                {copied ? 'Copied!' : 'Copy'}
              </Button>
              <Button variant="outline" size="sm" onClick={handleDownload} className="gap-1.5">
                <Download className="h-4 w-4" />
                Download
              </Button>
              {onSave && (
                <Button onClick={handleSave} variant="outline" size="sm" className="gap-1.5">
                  <BookOpen className="h-4 w-4" />
                  Save to Suite
                </Button>
              )}
              <Button variant="ghost" size="sm" onClick={generateTranscript} className="gap-1.5">
                <Sparkles className="h-4 w-4" />
                Regenerate
              </Button>
            </div>

            {/* Continue studying */}
            <div className="border-t border-border/50 pt-5">
              <p className="text-sm font-semibold text-muted-foreground mb-3 text-center">
                Continue exploring this study
              </p>
              <div className="flex flex-wrap gap-2 justify-center">
                <Button onClick={handleTakeToMindMap} size="sm" className="gap-2">
                  <Map className="h-4 w-4" />
                  Take to Mind Map
                  <ArrowRight className="h-3 w-3" />
                </Button>
                <Button variant="outline" size="sm" onClick={handleTakeToStudy} className="gap-2">
                  <BookOpen className="h-4 w-4" />
                  Take to Study Suite
                  <ArrowRight className="h-3 w-3" />
                </Button>
              </div>
            </div>
          </motion.div>
        )}

        {/* Stats bar */}
        <div className="flex items-center justify-center gap-6 pt-4 border-t border-border/50 text-sm">
          <span className="flex items-center gap-1.5 text-muted-foreground">
            <FileText className="h-3.5 w-3.5" />
            {entries.length} contributions
          </span>
          <span className="text-muted-foreground">
            {playerCount} player{playerCount !== 1 ? 's' : ''}
          </span>
          <span className="flex items-center gap-1 text-yellow-500 font-semibold">
            <Crown className="h-3.5 w-3.5" />
            {totalScore} pts
          </span>
        </div>
      </CardContent>
    </Card>
  );
}
