-- Insert remaining Old Testament book plans
INSERT INTO reading_plans (name, description, duration_days, plan_type, depth_mode, daily_schedule) VALUES
('Joshua in a Month', 'Conquest and inheritance with Victory themes and Cycle mapping', 30, 'book-monthly', 'focused', '{"estimated_time_minutes": 20, "book": "Joshua", "chapters_per_day": 0.8}'::jsonb),
('Judges in a Month', 'Cycles of rebellion and deliverance with Pattern recognition', 30, 'book-monthly', 'focused', '{"estimated_time_minutes": 20, "book": "Judges", "chapters_per_day": 0.7}'::jsonb),
('Ruth in a Month', 'Redemption story with Type and Parallel rooms', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 10, "book": "Ruth", "chapters_per_day": 0.14}'::jsonb),
('1 Samuel in a Month', 'Rise of kingship with Christ-centered concentration', 31, 'book-monthly', 'focused', '{"estimated_time_minutes": 20, "book": "1 Samuel", "chapters_per_day": 1.0}'::jsonb),
('2 Samuel in a Month', 'David''s reign with Great Controversy themes', 30, 'book-monthly', 'focused', '{"estimated_time_minutes": 20, "book": "2 Samuel", "chapters_per_day": 0.8}'::jsonb),
('1 Kings in a Month', 'Kingdom divided with Time Zone placement', 30, 'book-monthly', 'focused', '{"estimated_time_minutes": 25, "book": "1 Kings", "chapters_per_day": 0.73}'::jsonb),
('2 Kings in a Month', 'Fall of kingdoms with Cycle transitions', 30, 'book-monthly', 'focused', '{"estimated_time_minutes": 25, "book": "2 Kings", "chapters_per_day": 0.83}'::jsonb),
('1 Chronicles in a Month', 'Genealogy and temple with Sanctuary focus', 30, 'book-monthly', 'standard', '{"estimated_time_minutes": 20, "book": "1 Chronicles", "chapters_per_day": 0.97}'::jsonb),
('2 Chronicles in a Month', 'Temple history with Blue Room connections', 30, 'book-monthly', 'focused', '{"estimated_time_minutes": 25, "book": "2 Chronicles", "chapters_per_day": 1.2}'::jsonb),
('Ezra in a Month', 'Return and restoration with @Cy cycle emphasis', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 15, "book": "Ezra", "chapters_per_day": 0.36}'::jsonb),
('Nehemiah in a Month', 'Rebuilding walls with Leadership themes', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 15, "book": "Nehemiah", "chapters_per_day": 0.46}'::jsonb),
('Esther in a Month', 'Providence and deliverance with Great Controversy', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 15, "book": "Esther", "chapters_per_day": 0.36}'::jsonb),
('Job in a Month', 'Suffering and sovereignty with Fire Room engagement', 31, 'book-monthly', 'deep', '{"estimated_time_minutes": 30, "book": "Job", "chapters_per_day": 1.35}'::jsonb),
('Ecclesiastes in a Month', 'Wisdom and vanity with Personal Freestyle', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 15, "book": "Ecclesiastes", "chapters_per_day": 0.43}'::jsonb),
('Song of Solomon in a Month', 'Love and allegory with Christ-bride imagery', 28, 'book-monthly', 'deep', '{"estimated_time_minutes": 20, "book": "Song of Solomon", "chapters_per_day": 0.29}'::jsonb),
('Jeremiah in a Month', 'Prophecy and lament with DoL horizons', 31, 'book-monthly', 'deep', '{"estimated_time_minutes": 30, "book": "Jeremiah", "chapters_per_day": 1.68}'::jsonb),
('Lamentations in a Month', 'Mourning Jerusalem with emotional Fire Room', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 10, "book": "Lamentations", "chapters_per_day": 0.18}'::jsonb),
('Ezekiel in a Month', 'Visions and restoration with Sanctuary and Prophecy', 31, 'book-monthly', 'deep', '{"estimated_time_minutes": 30, "book": "Ezekiel", "chapters_per_day": 1.55}'::jsonb),
('Hosea in a Month', 'Love and faithfulness with Type exploration', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 15, "book": "Hosea", "chapters_per_day": 0.5}'::jsonb),
('Joel in a Month', 'Day of the Lord with DoL framework', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 10, "book": "Joel", "chapters_per_day": 0.11}'::jsonb),
('Amos in a Month', 'Justice and judgment with Social themes', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 12, "book": "Amos", "chapters_per_day": 0.32}'::jsonb),
('Obadiah in a Month', 'Judgment on Edom with Great Controversy', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 8, "book": "Obadiah", "chapters_per_day": 0.04}'::jsonb),
('Jonah in a Month', 'Mission and mercy with Personal Freestyle', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 10, "book": "Jonah", "chapters_per_day": 0.14}'::jsonb),
('Micah in a Month', 'Justice and restoration with Dimensions study', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 12, "book": "Micah", "chapters_per_day": 0.25}'::jsonb),
('Nahum in a Month', 'Fall of Nineveh with Time Zone placement', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 8, "book": "Nahum", "chapters_per_day": 0.11}'::jsonb),
('Habakkuk in a Month', 'Faith amid questions with Fire Room reflection', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 10, "book": "Habakkuk", "chapters_per_day": 0.11}'::jsonb),
('Zephaniah in a Month', 'Day of judgment with DoL emphasis', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 10, "book": "Zephaniah", "chapters_per_day": 0.11}'::jsonb),
('Haggai in a Month', 'Rebuild the temple with Sanctuary focus', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 8, "book": "Haggai", "chapters_per_day": 0.07}'::jsonb),
('Zechariah in a Month', 'Visions and Messiah with Prophecy Room', 28, 'book-monthly', 'deep', '{"estimated_time_minutes": 20, "book": "Zechariah", "chapters_per_day": 0.5}'::jsonb),
('Malachi in a Month', 'Final OT prophet with @CyC transition', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 10, "book": "Malachi", "chapters_per_day": 0.14}'::jsonb)
ON CONFLICT DO NOTHING;

-- Insert remaining New Testament book plans
INSERT INTO reading_plans (name, description, duration_days, plan_type, depth_mode, daily_schedule) VALUES
('1 Corinthians in a Month', 'Church life and gifts with Body of Christ themes', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 20, "book": "1 Corinthians", "chapters_per_day": 0.57}'::jsonb),
('2 Corinthians in a Month', 'Ministry and suffering with Personal application', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 18, "book": "2 Corinthians", "chapters_per_day": 0.46}'::jsonb),
('Galatians in a Month', 'Freedom in Christ with Fruit Room emphasis', 28, 'book-monthly', 'deep', '{"estimated_time_minutes": 15, "book": "Galatians", "chapters_per_day": 0.21}'::jsonb),
('Ephesians in a Month', 'Union with Christ with Sanctuary imagery', 28, 'book-monthly', 'deep', '{"estimated_time_minutes": 20, "book": "Ephesians", "chapters_per_day": 0.21}'::jsonb),
('Philippians in a Month', 'Joy in Christ with Fire Room engagement', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 15, "book": "Philippians", "chapters_per_day": 0.14}'::jsonb),
('Colossians in a Month', 'Supremacy of Christ with Concentration Room', 28, 'book-monthly', 'deep', '{"estimated_time_minutes": 15, "book": "Colossians", "chapters_per_day": 0.14}'::jsonb),
('1 Thessalonians in a Month', 'Second Coming hope with Time Zone study', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 12, "book": "1 Thessalonians", "chapters_per_day": 0.18}'::jsonb),
('2 Thessalonians in a Month', 'Day of the Lord with DoL framework', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 10, "book": "2 Thessalonians", "chapters_per_day": 0.11}'::jsonb),
('1 Timothy in a Month', 'Church leadership with pastoral themes', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 15, "book": "1 Timothy", "chapters_per_day": 0.21}'::jsonb),
('2 Timothy in a Month', 'Faithfulness and legacy with Fire Room', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 12, "book": "2 Timothy", "chapters_per_day": 0.14}'::jsonb),
('Titus in a Month', 'Sound doctrine with Fruit test application', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 10, "book": "Titus", "chapters_per_day": 0.11}'::jsonb),
('Philemon in a Month', 'Forgiveness and brotherhood with Personal Freestyle', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 8, "book": "Philemon", "chapters_per_day": 0.04}'::jsonb),
('James in a Month', 'Faith and works with Fruit Room focus', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 12, "book": "James", "chapters_per_day": 0.18}'::jsonb),
('1 Peter in a Month', 'Suffering and hope with Fire Room depth', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 15, "book": "1 Peter", "chapters_per_day": 0.18}'::jsonb),
('2 Peter in a Month', 'False teachers and Day of the Lord with @Re cycle', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 10, "book": "2 Peter", "chapters_per_day": 0.11}'::jsonb),
('1 John in a Month', 'Love and assurance with Dimensions study', 28, 'book-monthly', 'deep', '{"estimated_time_minutes": 15, "book": "1 John", "chapters_per_day": 0.18}'::jsonb),
('2 John in a Month', 'Truth and love with Fruit test', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 8, "book": "2 John", "chapters_per_day": 0.04}'::jsonb),
('3 John in a Month', 'Hospitality and truth with Personal application', 28, 'book-monthly', 'standard', '{"estimated_time_minutes": 8, "book": "3 John", "chapters_per_day": 0.04}'::jsonb),
('Jude in a Month', 'Contending for faith with Great Controversy', 28, 'book-monthly', 'focused', '{"estimated_time_minutes": 10, "book": "Jude", "chapters_per_day": 0.04}'::jsonb)
ON CONFLICT DO NOTHING;